In [37]:
import pandas as pd
import math
import numpy as np

In [62]:
test= pd.read_csv('./final_inference/lgbm_透天厝.csv')

In [146]:
# input = [303893.418, 2773228.853]
input = [169784.98804265473,2543493.999829864]
addr = '台南市東區青年路454號'
house_age = 33
far = 1.58
# '建物移轉總面積(坪)' : 3.484  '土地移轉總面積(坪)': 3.024 label :331437.79557039525 pred:307335.56736823893

In [147]:
compare = []
for idx,item in test.iterrows():
    tmpLoc = [float(item['x座標']),float(item['y座標'])]
    tmp = math.dist(tmpLoc, input)
    compare.append(tmp)

In [148]:
compare = np.array(compare)
idx = np.argpartition(compare,20)
print(idx)

[61292 61289 68231 ...     3     2     0]


In [149]:
output = test.iloc[idx[:20]]

In [177]:
output.iloc[5]['建物移轉總面積(坪)']

3.4838612664321573

In [150]:
output

Unnamed: 0  city_nm2  town_nm  交易車位  小坪數物件  建物型態  主要用途  主要建材  有無管理組織  \
61292       61292        14      172     0      0     4   191     6       0   
61289       61289        14      172     0      0     4   191     6       0   
68231       68231        14      172     0      0     4   191     6       0   
68230       68230        14      172     0      0     4   191     6       0   
68233       68233        14      172     0      0     4   191     6       0   
61290       61290        14      172     0      0     4   191     6       0   
61291       61291        14      172     0      0     4   191     6       0   
68232       68232        14      172     0      0     4   191     6       0   
82938       82938        14      172     0      0     4   588     6       0   
71421       71421        14      172     0      0     4   588     6       0   
82937       82937        14      172     0      0     4   588     6       0   
82936       82936        14      172     0      0     4   588     6       0   
82935       82935        14      172     0      0     4   588     6       0   
71420       71420        14      172     0      0     4   588     6       0   
92509       92509        14      172     0      0     4   588     6       0   
71422       71422        14      172     0      0     4   588     6       0   
71423       71423        14      172     0      0     4   588     6       0   
92510       92510        14      172     0      0     4   588     6       0   
92512       92512        14      172     0      0     4   588     6       0   
92511       92511        14      172     0      0     4   588     6       0   

       車位類別  ...  population_density  house_price_index  unemployment_rate  \
61292     2  ...              4049.0             100.69             0.0383   
61289     2  ...              8164.0             100.69             0.0383   
68231     2  ...             13927.0             100.08             0.0342   
68230     2  ...              8164.0             100.08             0.0342   
68233     2  ...              4049.0             100.08             0.0342   
61290     2  ...             13927.0             100.69             0.0383   
61291     2  ...              6330.0             100.69             0.0383   
68232     2  ...              6330.0             100.08             0.0342   
82938     2  ...              4049.0             101.59             0.0369   
71421     2  ...             13927.0             100.63             0.0381   
82937     2  ...              6330.0             101.59             0.0369   
82936     2  ...             13927.0             101.59             0.0369   
82935     2  ...              8164.0             101.59             0.0369   
71420     2  ...              8164.0             100.63             0.0381   
92509     2  ...              8164.0             105.39             0.0402   
71422     2  ...              6330.0             100.63             0.0381   
71423     2  ...              4049.0             100.63             0.0381   
92510     2  ...             13927.0             105.39             0.0402   
92512     2  ...              4049.0             105.39             0.0402   
92511     2  ...              6330.0             105.39             0.0402   

       econ_rate  lending_rate  land_tx_count  land_price  steel_id  \
61292     0.0361       0.01638       129010.0      101.12   1132.96   
61289     0.0361       0.01638       129010.0      101.12   1132.96   
68231     0.0342       0.01627       129999.0      100.11   1345.96   
68230     0.0342       0.01627       129999.0      100.11   1345.96   
68233     0.0342       0.01627       129999.0      100.11   1345.96   
61290     0.0361       0.01638       129010.0      101.12   1132.96   
61291     0.0361       0.01638       129010.0      101.12   1132.96   
68232     0.0342       0.01627       129999.0      100.11   1345.96   
82938     0.0299       0.01622       142271.0      100.65   1121.05  

In [155]:
compare_age = []
for idx,item in output.iterrows():
    tmpage = item['house_age']
    tmp = abs(tmpage - 33)
    compare_age.append(tmp)

In [156]:
compare_age = np.array(compare_age)
idx_age = np.argpartition(compare_age,10)
print(idx_age)

[ 1  5  2  3  4  0  6  7 13 16 15  9 12 11 14 10  8 17 18 19]


In [157]:
output_age = output.iloc[idx_age[:10]]

In [158]:
compare_far = []
for idx,item in output_age.iterrows():
    tmpage = item['far']
    tmp = abs(tmpage - 1.58)
    compare_far.append(tmp)

In [171]:
compare_far = np.array(compare_far)
idx_far = np.argpartition(compare_far,5)
print(idx_far)

[5 4 7 6 0 2 1 3 8 9]


In [172]:
output_far = output_age.iloc[idx_far[:5]]


In [173]:
sum = output_far['prediction'].mean()

In [174]:
sum

302861.74884639744

In [179]:
table = pd.DataFrame()

In [193]:
table['YIMBY_1000'] = output_far['n_c_1000']

In [194]:
table

x座標           y座標       容積率         屋齡  土地移轉總面積(坪)  \
61292  169784.988043  2.543494e+06  1.584118  33.232033    3.023834   
68233  169776.988039  2.543503e+06  1.584118  33.993155    3.023834   
68232  169776.988039  2.543503e+06  1.584118  33.993155    3.023834   
61291  169784.988043  2.543494e+06  1.584118  33.232033    3.023834   
61289  169784.988043  2.543494e+06  1.584118  33.232033    3.023834   

       建物移轉總面積(坪)  population_density     主建物面積           預測價格  YIMBY_1000  
61292    3.483861              4049.0  4.679535  305803.863048       112.0  
68233    3.483861              4049.0  4.679535  297682.725384       112.0  
68232    3.483861              6330.0  4.679535  297682.725384       112.0  
61291    3.483861              6330.0  4.679535  305803.863048       112.0  
61289    3.483861              8164.0  4.679535  307335.567368       112.0